name: Project_yeast
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.10
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.27.0
  - ca-certificates=2024.2.2
  - cairo=1.18.0
  - certifi=2024.2.2
  - charset-normalizer=3.3.2
  - click=8.1.7
  - coloredlogs=15.0.1
  - colormath=3.0.0
  - contourpy=1.2.0
  - cycler=0.12.1
  - expat=2.5.0
  - fastqc=0.12.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.49.0
  - freetype=2.12.1
  - future=1.0.0
  - gettext=0.21.1
  - gffread=0.12.7
  - giflib=5.2.1
  - graphite2=1.3.13
  - harfbuzz=8.3.0
  - hisat2=2.2.1
  - htslib=1.19
  - humanfriendly=10.0
  - humanize=4.9.0
  - icu=73.2
  - idna=3.6
  - importlib-metadata=7.0.1
  - jinja2=3.1.3
  - kaleido-core=0.2.1
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcups=2.3.3
  - libcurl=8.5.0
  - libdeflate=1.19
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.4
  - libgomp=13.2.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libopenblas=0.3.26
  - libpng=1.6.43
  - libsqlite=3.45.1
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libtiff=4.6.0
  - libuuid=2.38.1
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - lzstring=1.0.4
  - markdown=3.5.2
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - mathjax=2.7.7
  - matplotlib-base=3.8.3
  - mdurl=0.1.2
  - multiqc=1.21
  - munkres=1.1.4
  - ncurses=6.4
  - networkx=3.2.1
  - nspr=4.35
  - nss=3.98
  - numpy=1.26.4
  - openjdk=21.0.2
  - openjpeg=2.5.2
  - openssl=3.2.1
  - packaging=23.2
  - pcre2=10.42
  - perl=5.32.1
  - pillow=10.2.0
  - pip=24.0
  - pixman=0.43.2
  - plotly=5.19.0
  - pthread-stubs=0.4
  - pyaml-env=1.1.0
  - pygments=2.17.2
  - pyparsing=3.1.1
  - pysocks=1.7.1
  - python=3.11.8
  - python-dateutil=2.8.2
  - python-kaleido=0.2.1
  - python_abi=3.11
  - pyyaml=5.4.1
  - readline=8.2
  - requests=2.31.0
  - rich=13.7.1
  - rich-click=1.7.3
  - samtools=1.19
  - setuptools=69.1.1
  - simplejson=3.19.2
  - six=1.16.0
  - spectra=0.0.11
  - sqlite=3.45.1
  - subread=2.0.6
  - tenacity=8.2.3
  - tk=8.6.13
  - typing_extensions=4.10.0
  - tzdata=2024a
  - urllib3=2.2.1
  - wheel=0.42.0
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.7
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.11
  - xorg-libxt=1.3.0
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
