name: Project
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _sysroot_linux-64_curr_repodata_hack=3
  - alsa-lib=1.2.10
  - aragorn=1.2.41
  - argtable2=2.13
  - barrnap=0.9
  - bedtools=2.31.1
  - blast=2.14.1
  - blast-legacy=2.2.26
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.22.1
  - ca-certificates=2023.11.17
  - cairo=1.18.0
  - certifi=2023.11.17
  - charset-normalizer=3.3.2
  - click=8.1.7
  - clustalo=1.2.4
  - clustalw=2.1
  - coloredlogs=15.0.1
  - colormath=3.0.0
  - contourpy=1.2.0
  - curl=8.4.0
  - cycler=0.12.1
  - entrez-direct=16.2
  - expat=2.5.0
  - fastqc=0.12.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.44.3
  - freetype=2.12.1
  - future=0.18.3
  - gawk=5.3.0
  - gettext=0.21.1
  - giflib=5.2.1
  - gmp=6.3.0
  - graphite2=1.3.13
  - harfbuzz=8.3.0
  - hmmer=3.4
  - humanfriendly=10.0
  - humanize=4.8.0
  - icu=73.2
  - idna=3.4
  - importlib-metadata=6.8.0
  - infernal=1.1.4
  - jellyfish=2.2.10
  - jemalloc=4.5.0
  - jinja2=3.1.2
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcups=2.3.3
  - libcurl=8.4.0
  - libdb=6.2.32
  - libdeflate=1.19
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc=7.2.0
  - libgcc-ng=13.2.0
  - libgfortran=3.0.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.1
  - libgomp=13.2.0
  - libiconv=1.17
  - libidn11=1.34
  - libidn2=2.3.4
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libopenblas=0.3.24
  - libpng=1.6.39
  - libsqlite=3.44.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libtiff=4.6.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libzlib=1.2.13
  - llvm-openmp=8.0.1
  - lzstring=1.0.4
  - mafft=7.520
  - markdown=3.5.1
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - matplotlib-base=3.8.1
  - mdurl=0.1.0
  - minced=0.4.2
  - mpfr=4.2.1
  - multiqc=1.18
  - munkres=1.1.4
  - muscle=5.1
  - ncbi-vdb=3.0.0
  - ncurses=6.4
  - networkx=3.2.1
  - numpy=1.26.0
  - openjdk=21.0.1
  - openjpeg=2.5.0
  - openmp=8.0.1
  - openssl=3.1.4
  - packaging=23.2
  - paml=4.10.7
  - parallel=20230922
  - pcre=8.45
  - pcre2=10.42
  - perl=5.32.1
  - perl-algorithm-diff=1.201
  - perl-archive-tar=2.40
  - perl-base=2.23
  - perl-bio-asn1-entrezgene=1.73
  - perl-bio-coordinate=1.007001
  - perl-bio-featureio=1.6.905
  - perl-bio-samtools=1.43
  - perl-bio-searchio-hmmer=1.7.3
  - perl-bio-tools-phylo-paml=1.7.3
  - perl-bio-tools-run-alignment-clustalw=1.7.4
  - perl-bio-tools-run-alignment-tcoffee=1.7.4
  - perl-bioperl=1.7.8
  - perl-bioperl-core=1.7.8
  - perl-bioperl-run=1.007003
  - perl-business-isbn=3.007
  - perl-business-isbn-data=20210112.006
  - perl-carp=1.50
  - perl-class-data-inheritable=0.09
  - perl-common-sense=3.75
  - perl-compress-raw-bzip2=2.201
  - perl-compress-raw-zlib=2.202
  - perl-constant=1.33
  - perl-data-dumper=2.183
  - perl-db_file=1.858
  - perl-devel-stacktrace=2.04
  - perl-digest-hmac=1.04
  - perl-digest-md5=2.58
  - perl-encode=3.19
  - perl-encode-locale=1.05
  - perl-exception-class=1.45
  - perl-exporter=5.74
  - perl-exporter-tiny=1.002002
  - perl-extutils-makemaker=7.70
  - perl-file-listing=6.16
  - perl-file-path=2.18
  - perl-file-slurp-tiny=0.004
  - perl-file-sort=1.01
  - perl-file-spec=3.48_01
  - perl-file-temp=0.2304
  - perl-getopt-long=2.54
  - perl-html-parser=3.81
  - perl-html-tagset=3.20
  - perl-http-cookies=6.10
  - perl-http-daemon=6.16
  - perl-http-date=6.06
  - perl-http-message=6.36
  - perl-http-negotiate=6.01
  - perl-inc-latest=0.500
  - perl-io-compress=2.201
  - perl-io-html=1.004
  - perl-io-socket-ssl=2.075
  - perl-io-string=1.08
  - perl-io-tty=1.16
  - perl-io-zlib=1.14
  - perl-ipc-run=20200505.0
  - perl-json=4.10
  - perl-json-xs=2.34
  - perl-libwww-perl=6.67
  - perl-libxml-perl=0.08
  - perl-list-moreutils=0.430
  - perl-list-moreutils-xs=0.430
  - perl-lwp-mediatypes=6.04
  - perl-mime-base64=3.16
  - perl-module-build=0.4234
  - perl-net-http=6.22
  - perl-net-ssleay=1.92
  - perl-ntlm=1.09
  - perl-parent=0.241
  - perl-pathtools=3.75
  - perl-scalar-list-utils=1.63
  - perl-socket=2.027
  - perl-storable=3.15
  - perl-sub-uplevel=0.2800
  - perl-test-deep=1.130
  - perl-test-differences=0.71
  - perl-test-exception=0.43
  - perl-test-fatal=0.016
  - perl-test-most=0.38
  - perl-test-warn=0.37
  - perl-test-warnings=0.031
  - perl-text-diff=1.45
  - perl-time-local=1.35
  - perl-timedate=2.33
  - perl-tree-dag_node=1.32
  - perl-try-tiny=0.31
  - perl-types-serialiser=1.01
  - perl-uri=5.17
  - perl-url-encode=0.03
  - perl-www-robotrules=6.02
  - perl-xml-dom=1.46
  - perl-xml-dom-xpath=0.14
  - perl-xml-namespacesupport=1.12
  - perl-xml-parser=2.44_01
  - perl-xml-regexp=0.04
  - perl-xml-sax=1.02
  - perl-xml-sax-base=1.09
  - perl-xml-sax-expat=0.51
  - perl-xml-simple=2.25
  - perl-xml-xpathengine=0.14
  - pillow=10.1.0
  - pip=23.3.1
  - pixman=0.42.2
  - poa=2.0
  - prodigal=2.6.3
  - prokka=1.14.6
  - pthread-stubs=0.4
  - pyaml-env=1.1.0
  - pygments=2.16.1
  - pyparsing=3.1.1
  - pysocks=1.7.1
  - python=3.11.6
  - python-dateutil=2.8.2
  - python_abi=3.11
  - pyyaml=5.4.1
  - readline=8.2
  - requests=2.31.0
  - rich=13.7.0
  - rich-click=1.7.1
  - setuptools=68.2.2
  - simplejson=3.19.2
  - six=1.16.0
  - spades=3.15.5
  - spectra=0.0.11
  - sysroot_linux-64=2.17
  - t-coffee=12.00.7fb08c2
  - tbl2asn-forever=25.7.2f
  - tk=8.6.13
  - typing_extensions=4.8.0
  - tzdata=2023c
  - urllib3=2.1.0
  - viennarna=2.4.7
  - wget=1.20.3
  - wheel=0.41.3
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.7
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.11
  - xorg-libxt=1.3.0
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
